### ISSUE TITLE
Review ATO checklist

### ISSUE THREAD

**Issue by UchMok** [18F/civil-rights#230]
## Description

[Tasks to launch](https://docs.google.com/document/d/1q2oSHdIvokDv9W5NV3G7MKQTSuS6VdT9VaTTotw545M/edit#heading=h.izzlymjneeqo)

## Definition of done
- [x] Identify thin slice and product roadmap
- [x] @LindsayYoung to schedule a meeting to check in w @danielyi18 , @dwechsle, Gary, et al (?) about what is in scope for our ATO tasks and call out anything outstanding from the DOJ side
- [x] @dwechsle to follow up w/ Gary on any additional attendees needed

## Attachments
[title](URL)

**Comment by LindsayYoung** [comment]
Outcomes of the initial meeting  

- Darren will send Sean the current docs 
- Configure logging (tech task)
- Contingency plan/ Back up plan (documentation task)
- Data masking - as needed
- Define user categories- probably start with something like admin, staff and public(documentation task)
- Privacy assessment (documentation task Dan is working on it)
- SPP - will generate in CSAM  (documentation task)

See doc for full detail https://docs.google.com/document/d/1q2oSHdIvokDv9W5NV3G7MKQTSuS6VdT9VaTTotw545M/edit#

**Comment by UchMok** [comment]
Gary gave @dweschle Sean's contact info to talk to him about ATO tasks. @LindsayYoung and @dweschle met with Sean this Monday and seem to have all things in scope w.r.t. ATO. We are to reach out to Gary if we have any roadblocks.
