### ISSUE TITLE
Complete Team Charter & Communication Plan Checklist

### ISSUE THREAD

**Issue by UchMok** [18F/civil-rights#233]
## Definition of done
- [ ] Confirm DOJ core team member time allocation from Sprint 1
- [x] Update section POC list and add as information radiator
- [x] Update Product Champion POCs and add as information radiator
- [x] Confirm Project Management Tool - zenhub
- [ ] Confirm technical framework
- [x] Sync DOJ + 18F calendars
- [ ] Discuss OOO/Leave protocol
- [ ] Discuss team core ceremonies (purpose, cadence, participants)
- [ ] Discuss team practices and story lifecycle
- [ ] Confirm story, tech task, defect template

## Attachments
[title](URL)
