### ISSUE TITLE
Roadmap/scope 

### ISSUE THREAD

**Issue by lalitha-jonnalagadda** [18F/civil-rights#373]
## Description

In the past, the 18F team had presented a thin slice scope as well as a Now/Next/Later roadmap to the sections. The sections have requested more clarity on the potential deliverable scope by the end of the engagement. 

## Definition of done
- [x] Lalitha to sync with Uchenna on this request 
- [x] Prepare a draft of the notes from Uchenna +Lalitha conversation 
- [x] Sync with Dan before presenting the notes to sections

**Comment by lalitha-jonnalagadda** [comment]
Spoke to Uchenna and Dan on the approach to continue developing user stories and use the deep dive sessions to reiterate the scope and roadmap. Closing this card
